apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/mysql
  - auth-configmap.yaml
  - ../../base/auth-server-statefulset
  - ../../base/auth-client

labels:
  - pairs:
      app.kubernetes.io/name: java-auth
      app.kubernetes.io/instance: java-auth
      app.kubernetes.io/part-of: java-auth-system
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: true
