apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo-stack
resources:
  - namespace.yaml
  - java-server.yaml
  - csharp-weather.yaml
  - node-server.yaml
  - php-server.yaml
  - gateway.yaml
  - traffic-client.yaml
configMapGenerator:
  - name: traffic-client-script
    files:
      - traffic-client/client
    options:
      disableNameSuffixHash: true
