apiVersion: v1
kind: Service
metadata:
  name: java-auth-service
  labels:
    app: java-auth
spec:
  clusterIP: None
  selector:
    app: java-auth
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
