apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: smart-replace-demo
  app.kubernetes.io/managed-by: kustomize

resources:
  - cart-service/deployment.yaml
  - cart-service/service.yaml
  - cart-service/configmap.yaml
  - warehouse-service/deployment.yaml
  - warehouse-service/service.yaml
  - client/deployment.yaml
  - client/configmap.yaml
  - secrets/jwt-secret.yaml
